services:
  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - wp_db:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - FSETID
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - SYS_NICE
    networks:
      - private_network

  web:
    build:
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    cap_drop:
      - NET_RAW
    networks:
      - public_network
    volumes:
      - wp_data:/var/www/html:ro

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0-fpm-alpine
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: '1'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '512M');
    networks:
      - public_network
      - private_network
    cap_drop:
      - NET_RAW

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

volumes:
  wp_db: {}
  wp_data: {}
