# not working

name: Build and upload site

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
  AWS_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
  AWS_REGION: ${{ secrets.S3_REGION }}
  AWS_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_TELEGRAM_STORAGE_FILENAME: ${{ secrets.S3_TELEGRAM_STORAGE_FILENAME }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
  TELEGRAM_CHANNEL_URL: ${{ secrets.TELEGRAM_CHANNEL_URL }}
  ONLY_POSTS_WITH_TAGS: ${{ secrets.ONLY_POSTS_WITH_TAGS }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run prod

    - name: Deploy to s3
      uses: reggionick/s3-deploy@v4
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_REGION }}
